#!/bin/bash

function canonicalize
{
        cd -P -- "$(dirname -- "$1")" &&
        printf '%s\n' "$(pwd -P)/$(basename -- "$1")"
}

basedir=`canonicalize $0`
basedir=`dirname $basedir`

mkdir -p $basedir/../../webRoot
webRoot=`canonicalize $basedir/../../webRoot`
gsPath=`canonicalize $basedir/../../DIRAC | sed 's:DIRAC$:etc/grid-security:g'`

externalsRoot=`dirname $basedir`
# mkdir -p $basedir/../etc
lighttpdConfPath=`canonicalize $externalsRoot/etc/lighttpd.conf`
cat $basedir/lighttpd.conf | sed "s:%GSLOCATION%:${gsPath}:g" | sed "s:%WEBROOT%:${webRoot}:g" > $lighttpdConfPath

for i in www log compress rrdtool
do
  mkdir -p $webRoot/$i
done

cat << 'EOF' > $webRoot/www/index.html
<html><head><meta HTTP-EQUIV="REFRESH" content="0; url=DIRAC/"></head></html>
EOF

lighttpdCmd="${externalsRoot}/sbin/lighttpd -m ${externalsRoot}/lib -f ${lighttpdConfPath}"
lighttpdSvcBin=`canonicalize $externalsRoot/bin/lighttpdSvc.sh`

#
# Generate the lighttpd start script now
#

cat << EOF > $lighttpdSvcBin
#!/bin/bash

export OPENSSL_CONF=$gsPath

gsCerts=$gsPath/certificates
if ! test -d \$gsCerts; then
  echo \$gsCerts does not exit
  mkdir -p $gsPath
  gsCerts=/etc/grid-security/certificates
  if ! test -d $gsCerts; then
    echo \$gsCerts does not exist neither
    exit 1
  fi  
fi

rm -f $gsPath/allCAs.pem
copiedCAs=0
invalidCAs=0
echo "Copying CA certificates into $gsPath/allCAs.pem..."
for cert in \$gsCerts/*.0
do
  ossle="openssl x509 -noout -in \${cert}"
  if \${ossle} -checkend 3600; then
	cat \${cert} >> $gsPath/allCAs.pem
	copiedCAs=\`expr "\${copiedCAs}" + "1"\`
  else
    echo " - CA \${cert} is expired"
    invalidCAs=\`expr "\${invalidCAs}" + "1"\`
  fi
done
echo " + There are \${invalidCAs} invalid CA certificates in $gsPath/allCAs.pem"
echo " + Copied \${copiedCAs} CA certificates into $gsPath/allCAs.pem"

certOK=0
for prefix in host service
do
 if [ -f $gsPath/\${prefix}cert.pem -a -f $gsPath/\${prefix}key.pem ]; then
  cat $gsPath/\${prefix}cert.pem > $gsPath/webcert.pem
  echo >> $gsPath/webcert.pem
  cat $gsPath/\${prefix}key.pem >> $gsPath/webcert.pem
  certOK=1
 fi
done

if [ "\$certOK" == "0" ]; then
 echo "Could not regenerate webcert.pem from host[cert|key].pem nor service[cert|key].pem"
 exit 1
fi

echo "$gsPath/webcert.pem and $gsPath/allCAs.pem seem OK"

if ! ${lighttpdCmd} -t; then
  echo "${lighttpdConfPath} has a problem. Please fix it."
  exit 1
fi

echo "Starting lighttpd..."
exec ${lighttpdCmd} -D
EOF

chmod +x $lighttpdSvcBin

